### 단건 조회
GET localhost:8080/items/1

### 전체 조회
GET localhost:8080/items

### 물건추가
POST localhost:8080/items
Content-Type: application/json

{
  "name": "test mouse",
  "description": "test mouse description",
  "price": 100000
}

### 물건수정
PUT localhost:8080/items/1
Content-Type: application/json

{
  "name": "event mouse",
  "description": "sale!",
  "price": 10000
}

### 물건 삭제
DELETE localhost:8080/items/1

### 페이징 조회
GET localhost:8080/items/search?q=mo

### 페이징 조회
GET localhost:8080/items/search?q=mo&page=1&size=5